create public synonym days_per_month for days_per_month;
create public synonym new_employee_type for new_employee_type;
create public synonym emp_details_type for emp_details_type;
create public synonym app_users_seq for app_users_seq;
create public synonym emp_id_seq for emp_id_seq;		
create public synonym restant_days for restant_days;	
create public synonym passed_attributions for passed_attributions;	
create public synonym skill_matrix for skill_matrix;	
create public synonym user_atributions for user_atributions